<a href="https://colab.research.google.com/github/AyberkDnmez/Python-Programming-for-Data-Science/blob/main/Python_ile_Veri_Analizi_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Başlık : NumPy Array'i Oluşturma (Creating NumPy Arrays)

# Aşağıda yapılan işlemde sıfırdan bir array oluşturma işlemi array metoduyla gerçekleştirilmektedir.

import numpy as np

np.array([1, 2, 3, 4, 5])


array([1, 2, 3, 4, 5])

In [5]:
# Oluşturulan yapının tipini sorgulayalım.

type(np.array([1, 2, 3, 4, 5]))

numpy.ndarray

In [6]:
# Sıfırdan array oluşturmanın başka bazı yöntemleri de mevcuttur. Aşağıda bazılarının örnekleri gösterilmektedir.

# 1- zeros metodu : Girdiğimiz sayı değeri kadar 0 lardan oluşan array oluşturur. Aşağıda 10 tane 0 dan oluşan ve tipleri integer olan bir array oluşturulmaktadır.

np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# 2- randint metodu : Önce random modulünü çağırmamız gerekmektedir. Ardından randint metodu çağrılır. Hangi sınırdan hangi sınıra kadar array oluşturulmak

# istendiği bilgileri girilir. Ardından size ile kaç tane seçim yapılmak isteniyorsa onun bilgisi girilir. Aşağıda yapılan işlem alt limiti 0 üst limiti 10

# olan ve 10 tane rastgele sayı (integer) içeren bir array oluşturma işlemidir.

np.random.randint(0, 10, size = 10)

array([8, 7, 0, 0, 5, 2, 7, 1, 7, 1])

In [11]:
# 3- normal metodu : Eğer ki belirli bir istatistiksel dağılıma göre sayı üretmek istersek bunu random modulündeki normal metoduyla gerçekleştirebiliriz.

# Aşağıda ortalaması 10, standart sapması 4, 3 x 4 lük normal dağılımlı bir array oluşturulmmuştur.

np.random.normal(10, 4, (3, 4))

array([[ 3.03326328, 12.36605078, 11.89603808, 14.62581107],
       [13.84969167,  0.42585994,  7.61946371, 12.6005929 ],
       [ 8.9472778 , 10.63615366, 12.39580984, 12.78439319]])

In [ ]:
# Diğer sıfırdan array oluşturma metodları için --> raandom modulünü inceleyebilirsin.

# Yaygın kullanım sıfırdan array oluşturma değildir.

In [13]:
# Başlık : NumPy Array Özellikleri (Attributes of NumPy Arrays)

import numpy as np

# ndim : Boyut Sayısı
# shape : Boyut Bilgisi
# size : Toplam Eleman Sayısı
# dtype : Array Veri Tipi

a = np.random.randint(10, size=5)

a


array([7, 5, 4, 7, 1])

In [14]:
# Boyut sayısına erişmek için :

# Tek boyutludur.

a.ndim

1

In [15]:
# Boyut bilgisine ulaşmak için :

# Tek boyutludur ve içinde 5 eleman vardır. Burada 2 boyut olsaydı her boyuttaki eleman sayısı gelecekti.

a.shape

(5,)

In [16]:
# Toplam eleman sayısına ulaşmak için :

a.size

5

In [17]:
# NumPy arrayin tuttuğu verilerin tip bilgisine ulaşmak için :

a.dtype

dtype('int64')

In [20]:
# Başlık : Yeniden Şekillendirme (Reshaping)

# Elimizdeki numpy arrayinin boyutunu değiştirmek istediğimizde reshape metodunu kullanırız.

np.random.randint(1, 10, size=9)

array([9, 2, 7, 6, 9, 7, 4, 5, 6])

In [21]:
# Diyelim ki yukarıdaki arrayi iki boyutlu bir arraye çevirmek istiyoruz. Örneğin 3 x 3 lük bir arraye çevirelim.

np.random.randint(1, 10, size=9).reshape(3, 3)

array([[8, 8, 6],
       [9, 1, 7],
       [4, 3, 2]])

In [23]:
# Bir de aynı işlemi atama işlemiyle birlikte gerçekleştirelim.

# Arrayi oluşturalım.

ar = np.random.randint(1, 10, size=9)

ar


array([6, 5, 8, 8, 4, 8, 3, 1, 1])

In [25]:
# Arrayi yeniden şekillendirelim.

ar.reshape(3,3)

array([[6, 5, 8],
       [8, 4, 8],
       [3, 1, 1]])