<a href="https://colab.research.google.com/github/AyberkDnmez/Python-Programming-for-Data-Science/blob/main/Python_ile_Veri_Analizi_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Başlık : NumPy Array'i Oluşturma (Creating NumPy Arrays)

# Aşağıda yapılan işlemde sıfırdan bir array oluşturma işlemi array metoduyla gerçekleştirilmektedir.

import numpy as np

np.array([1, 2, 3, 4, 5])


array([1, 2, 3, 4, 5])

In [ ]:
# Oluşturulan yapının tipini sorgulayalım.

type(np.array([1, 2, 3, 4, 5]))

numpy.ndarray

In [ ]:
# Sıfırdan array oluşturmanın başka bazı yöntemleri de mevcuttur. Aşağıda bazılarının örnekleri gösterilmektedir.

# 1- zeros metodu : Girdiğimiz sayı değeri kadar 0 lardan oluşan array oluşturur. Aşağıda 10 tane 0 dan oluşan ve tipleri integer olan bir array oluşturulmaktadır.

np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# 2- randint metodu : Önce random modulünü çağırmamız gerekmektedir. Ardından randint metodu çağrılır. Hangi sınırdan hangi sınıra kadar array oluşturulmak

# istendiği bilgileri girilir. Ardından size ile kaç tane seçim yapılmak isteniyorsa onun bilgisi girilir. Aşağıda yapılan işlem alt limiti 0 üst limiti 10

# olan ve 10 tane rastgele sayı (integer) içeren bir array oluşturma işlemidir.

np.random.randint(0, 10, size = 10)

array([8, 7, 0, 0, 5, 2, 7, 1, 7, 1])

In [ ]:
# 3- normal metodu : Eğer ki belirli bir istatistiksel dağılıma göre sayı üretmek istersek bunu random modulündeki normal metoduyla gerçekleştirebiliriz.

# Aşağıda ortalaması 10, standart sapması 4, 3 x 4 lük normal dağılımlı bir array oluşturulmmuştur.

np.random.normal(10, 4, (3, 4))

array([[ 3.03326328, 12.36605078, 11.89603808, 14.62581107],
       [13.84969167,  0.42585994,  7.61946371, 12.6005929 ],
       [ 8.9472778 , 10.63615366, 12.39580984, 12.78439319]])

In [ ]:
# Diğer sıfırdan array oluşturma metodları için --> raandom modulünü inceleyebilirsin.

# Yaygın kullanım sıfırdan array oluşturma değildir.

In [ ]:
# Başlık : NumPy Array Özellikleri (Attributes of NumPy Arrays)

import numpy as np

# ndim : Boyut Sayısı
# shape : Boyut Bilgisi
# size : Toplam Eleman Sayısı
# dtype : Array Veri Tipi

a = np.random.randint(10, size=5)

a


array([7, 5, 4, 7, 1])

In [ ]:
# Boyut sayısına erişmek için :

# Tek boyutludur.

a.ndim

1

In [ ]:
# Boyut bilgisine ulaşmak için :

# Tek boyutludur ve içinde 5 eleman vardır. Burada 2 boyut olsaydı her boyuttaki eleman sayısı gelecekti.

a.shape

(5,)

In [ ]:
# Toplam eleman sayısına ulaşmak için :

a.size

5

In [ ]:
# NumPy arrayin tuttuğu verilerin tip bilgisine ulaşmak için :

a.dtype

dtype('int64')

In [ ]:
# Başlık : Yeniden Şekillendirme (Reshaping)

# Elimizdeki numpy arrayinin boyutunu değiştirmek istediğimizde reshape metodunu kullanırız.

np.random.randint(1, 10, size=9)

array([9, 2, 7, 6, 9, 7, 4, 5, 6])

In [ ]:
# Diyelim ki yukarıdaki arrayi iki boyutlu bir arraye çevirmek istiyoruz. Örneğin 3 x 3 lük bir arraye çevirelim.

np.random.randint(1, 10, size=9).reshape(3, 3)

array([[8, 8, 6],
       [9, 1, 7],
       [4, 3, 2]])

In [ ]:
# Bir de aynı işlemi atama işlemiyle birlikte gerçekleştirelim.

# Arrayi oluşturalım.

ar = np.random.randint(1, 10, size=9)

ar


array([6, 5, 8, 8, 4, 8, 3, 1, 1])

In [ ]:
# Arrayi yeniden şekillendirelim.

ar.reshape(3,3)

array([[6, 5, 8],
       [8, 4, 8],
       [3, 1, 1]])

In [4]:
# Başlık : Index işlemleri

# Index Seçimi (Index Selection)

import numpy as np
a = np.random.randint(10, size=10)

a

array([9, 3, 4, 4, 0, 0, 9, 2, 3, 0])

In [5]:
# 0.elemana gitmek istediğimizi düşünelim.

a[0]

# Gördüğümüz gibi liste veri yapılarına oldukça benzerdir.

9

In [6]:
# Birden fazla elemanı seçmek istediğimizi düşünelim. Bu işlem de listelerdeki gibidir.

a[0:5]

array([9, 3, 4, 4, 0])

In [7]:
# Belirli bir indexteki elemanı değiştirmek istediğimizi düşünelim.

a[0] = 999

a

array([999,   3,   4,   4,   0,   0,   9,   2,   3,   0])

In [9]:
# Elimizde 2 boyutlu arrayler olursa burada seçim işlemlerini nasıl gerçekleştiririz ?

m = np.random.randint(10, size=(3,5))

m

array([[7, 2, 5, 2, 7],
       [9, 2, 8, 4, 9],
       [7, 4, 8, 4, 9]])

In [10]:
# Dikkat ! Aşağıdaki işlemde virgülden öncesi satırları, virgülden sonrası sütunları temsil etmektedir. Dolayısıyla elimizde 2 boyutlu bir array

# olduğunda hem satır bilgisini hem sütun bilgisini vermemiz gerekmektedir.

m[0, 0]



7

In [11]:
m[1, 1]

2

In [12]:
m[2, 3]

4

In [14]:
# Eleman değiştirme işlemi gerçekleştirelim.

m [2, 3] = 999

m

array([[  7,   2,   5,   2,   7],
       [  9,   2,   8,   4,   9],
       [  7,   4,   8, 999,   9]])

In [16]:
# Buraya float eklemek istesek ne olurdu ? Görelim.

m[2, 3] = 2.9

m

# NumPy fix type arraydir. NumPyı hızlı kılan verimli veri saklama yönüdür. NumPy tek tip veri saklar. Bu yüzden girilen bu float değerin diğer verilerin

# tipiyle uyumlu olması gerekir. Bu yüzden bunu 2 olarak arraye dahil eder.

array([[7, 2, 5, 2, 7],
       [9, 2, 8, 4, 9],
       [7, 4, 8, 2, 9]])

In [17]:
# İki boyutlu arraylerde slicing işlemini görelim.

m[:, 0]

array([7, 9, 7])

In [18]:
m[1, :]

array([9, 2, 8, 4, 9])

In [19]:
m[0:2, 0:3]

array([[7, 2, 5],
       [9, 2, 8]])

In [22]:
# Başlık : Fancy Index

# Aşağıdaki ifade 0 dan 30 a kadar 3 er 3 er artan array oluştur anlamına gelmektedir. Belirli bir adım boyunca array oluşturmak için kullanılabilen

# bir metotdur.

import numpy as np

v = np.arange(0, 30, 3)

v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [23]:
# Birinci indeksteki elemana gidelim..

v[1]

3

In [24]:
# Dördüncü indeksteki elemana gidelim.

v[4]

12

In [ ]:
# Fancy Index Ne İşe Yarar ?

# Fancy Index bir NumPy arrayine, bir liste girdiğinizde, ki bu liste indeks numarası ya da true false ifadelerini de tutuyor olablir; bize kolay bir şekilde

# seçim işlemi sağlar.

# Fancy Indexi kullanalım.

In [25]:
catch = [1, 2, 3]

v[catch]

array([3, 6, 9])

In [27]:
# Başlık : NumPy Koşullu İşlemler (Conditions on NumPy)

import numpy as np

v = np.array([1, 2, 3, 4, 5])

v



array([1, 2, 3, 4, 5])

In [30]:
# Array içindeki 3 ten küçük değerlere erişmek istediğimizi düşünelim.

# 1. Çözüm : Klasik Döngü ile

ab = []

for i in v:
  print(i)

for i in v:
  if i < 3:
    ab.append(i)

ab


1
2
3
4
5


[1, 2]

In [31]:
# Peki bunu NumPy ile nasıl gerçekleştiririz ?

# Önce aşağıdaki işlemin sonucunu gözlemleyelim.

v < 3

array([ True,  True, False, False, False])

In [32]:
# Bu işlemin verdiği sonuca göre, bu sorguyu fancy index olarak kullanalım.

v[v < 3]

array([1, 2])

In [ ]:
# Bu senaryo genişletilebilir. Örneğin : 3 e eşit olmayanlar gelsin denilebilir.

v[ v =! 3]